name: polymaker
author: Yusril Rapsanjani <yuranicorp@gmail.com>
version: 0.0.5
homepage: https://github.com/yusriltakeuchi/polymaker.git
description: Polymaker is a flutter package used to get a list of locations for polygon google maps
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  google_maps_flutter: ^1.1.1
  location: ^3.2.4
  provider: ^4.3.3
  simple_animations: ^2.5.1
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/
    - assets/map_style.txt
